platform :ios, '14.0'
use_frameworks!

inhibit_all_warnings!

target 'iOSExamTest' do
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'
  pod 'GrowingTextView', '0.7.2'
  # Firebase
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
